import PDFDocument from "pdfkit-table";
import fs from 'fs'
import fsa from "fs/promises";
import { transfer_demand } from "./transferDemand.js";
import { createTable } from "./table.js";
import { transfer_approval } from "./transfer_approval.js";


async function read_const(){
  const data = await fsa.readFile("constant_data.json")
  return JSON.parse(data.toString())
}



let header = {
  type : "t_approval",
  letter_no : 'ODD/UG/UG(PT)/PG - TR,RCT/SA2-2/2022-2023',
  date : '09.09.2022',
  to : ["The Dean of Constituent Colleges / Regional Campus /","The Principal of Government / Government Aided / Self-Financing / ","Autonomous Engineering Colleges (Annexure enclosed)."],   // to array
  sub_ug_or_pg : 'UG',
  Ref : 'D.T.E’s Letter No. 22100 / J4 / 2022, dated: 25.08.2022.',  // array
  year : "2021-2022",
  no_of_students : 50,
  copy_to :["The Controller of Examinations, Anna University Chennai – 25","Stock file"],
  odd_or_even : "ODD",
  amount : "2000"
  //copy to array
}


// let rows = [["1 V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"],["1","V.RAJARAJESHWARI","923820105029",	"V",	"B.E (ELECTRICAL & ELECTRONICSENGINEERING)","MANGAYARKARASI COLLEGE OF ENGINEERING","PRIYADARSHINI ENGINEERING COLLEGE"]];
// sno auto

const doc = new PDFDocument({size:"A4",margins:{left:50,right:50,top:20,bottom:50}});
const constants =await read_const()

if(header.type === 't_demand')  
  await transfer_demand(doc,header,constants)

if(header.type === 't_approval')
  await transfer_approval(doc,header,constants)


